spring.application.name=ingush-spell-checker
server.port=8080

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.info.title=ГIалгIай мотт — Spell Checker API
springdoc.info.description=REST API для проверки орфографии ингушского языка
springdoc.info.version=1.0.0
